services:
  - type: web
    name: es1-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromGroup: PORT
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        fromGroup: MONGODB_URI
